# Generated by Django 5.1.13 on 2025-12-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_thread_is_trashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadaccess',
            name='origin',
            field=models.CharField(choices=[('received', 'received'), ('sent', 'sent'), ('shared', 'shared'), ('forwarded', 'forwarded')], default='received', max_length=20, verbose_name='origin'),
        ),
    ]
