# Generated by Django 5.1.8 on 2025-07-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_thread_count_draft_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['slug'], 'verbose_name': 'label', 'verbose_name_plural': 'labels'},
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, null=True, max_length=255, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='subject',
            field=models.CharField(blank=True, null=True, max_length=255, verbose_name='subject'),
        ),
    ]
